# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
# spec:
#   selector:
#     matchLabels:
#       app: nginx
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:latest
#           volumeMounts:
#             - name: nginx-config-volume
#               mountPath: /etc/nginx/conf.d/default.conf
#               subPath: default.conf
#       volumes:
#         - name: nginx-config-volume
#           configMap:
#             name: nginx-config
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       targetPort: 8080
#   selector:
#     app: nginx


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8080
    # nodePort: 30080
  type: LoadBalancer
