apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://movie-service:8002/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast-service:8003/api/v1/casts;
      }
    }
